unlet! skip_defaults_vim
" source $VIMRUNTIME/defaults.vim

set shell=/usr/bin/bash

call dirsettings#Install()

filetype off
syntax off

call pathogen#runtime_append_all_bundles()

filetype plugin indent on

syntax on
syntax sync minlines=256

"set nocompatible

" Tabs instead of spaces
set noexpandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2

set autoindent
set nostartofline

set encoding=utf-8
"set termencoding=utf-8

set hidden
set scrolloff=3
set showmode
set showcmd
"set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set undofile

set wildmenu
set wildmode=list:longest
set wildignore=*.swp,*.bak
set wildignore+=*.pyc,*.class,*.sln,*.Master,*.csproj,*.csproj.user,*.cache,*.dll,*.pdb,*.min.*
set wildignore+=*/.git/**/*,*/.hg/**/*,*/.svn/**/*
set wildignore+=tags
set wildignore+=*.tar.*
set wildignorecase

set splitbelow
set splitright

" Show me what I'm doing
set concealcursor="nc"
set conceallevel=0

let mapleader = " "
let g:mapleader = " "

nnoremap ; :
vnoremap ; :
nnoremap / /\v
vnoremap / /\v
nnoremap <C-e> :e#<CR>
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
" nnoremap <leader><space> :noh<cr>
map <tab> g%
cmap w!! %!sudo tee > /dev/null %

set statusline=%<\ %f\ %{fugitive#statusline()}\ %r%y%m%=\ Line:\ \%l\/\%L\ Column:\ \%c

set wrap
set textwidth=79
set formatoptions=qrn1
"set colorcolumn=79

set list
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·

set nuw=6
set number
set relativenumber
set cursorline
set clipboard^=unnamed					" X11 System Clipboard
set autowrite
set autoread

" Limit the amount of filesystem events
set nowritebackup
set nobackup
"set noswapfile

" Save your swp files to a less annoying place than the current directory.
" If you have .vim-swap in the current directory, it'll use that.
" Otherwise it saves it to ~/.vim/swap, ~/tmp or .
if isdirectory($HOME . '/.vim/swap') == 0
	:silent !mkdir -p ~/.vim/swap >/dev/null 2>&1
endif
set directory=./.vim-swap//
set directory+=~/.vim/swap//
set directory+=~/tmp//
set directory+=.

" viminfo stores the the state of your previous editing session
set viminfo+=n~/.vim/viminfo

if exists("+undofile")
  " undofile - This allows you to use undos after exiting and restarting
  " This, like swap and backups, uses .vim-undo first, then ~/.vim/undo
  " :help undo-persistence
  " This is only present in 7.3+
  if isdirectory($HOME . '/.vim/undo') == 0
    :silent !mkdir -p ~/.vim/undo > /dev/null 2>&1
  endif
  set undodir=./.vim-undo//
  set undodir+=~/.vim/undo//
  set undofile
endif

augroup vimrcEx
	au!

	" When editing a file, always jump to the last known cursor position.
	" Don't do it when the position is invalid or when inside an event handler
	" (happens when dropping a file on gvim).
	autocmd BufReadPost *
				\ if line("'\'") > 0 && line("'\'") <= line("$") |
				\ exe "normal g`\"" |
				\ endif

	au BufWritePre * :%s/\s\+$//e	 " Remove trailing whitespace upon saving
	" au FocusLost,InsertLeave * bufdo call functions#AutoSave()
	" au InsertLeave * :wa
augroup END

" Fix cursor when entering/leaving from ZSH
" autocmd VimEnter * silent exec "! echo -ne '\e[2 q'"
" autocmd VimLeave * silent exec "! echo -ne '\e[6 q'"

" Relies on Xresources for colours
set background=dark
let base16colorspace=256
colorscheme base16-grayscale-dark

nnoremap <leader>a :Ack

" Select what you just pasted
nnoremap <leader>v V`]

" use jj to exit insert mode
inoremap jj <ESC>

" Create vertical split and switch to it
nnoremap <leader>w <C-w>v<C-w>l

" Split window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Move around split lines
nnoremap j gj
nnoremap k gk

" Fast editing of the .vimrc
map <leader>e :e! ~/.vim/vimrc<CR>

" " Periodical auto-save
" " Write to disk after 1 second of inactivity, once every 15 seconds.
" au BufRead,BufNewFile * let b:last_autosave=localtime()
" au CursorHold * call UpdateFile()
" au BufWritePre * let b:last_autosave=localtime()
" set updatetime=1000
" function! UpdateFile()
" 	if exists("b:last_autosave") && ((localtime() - b:last_autosave) >= 15)
" 		update
" 		let b:last_autosave=localtime()
" 	endif
" endfunction

" au FileType html,xml,xsl source ~/.vim/scripts/closetag.vim
" iabbrev </ </<C-X><C-O>

" Vim style lorem ipsum generator
inoreabbrev lorem Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.

" Ruby stuff
autocmd FileType ruby
					\ if expand('%') =~# '_test\.rb$' |
					\   compiler rubyunit | setl makeprg=testrb\ \"%:p\" |
					\ elseif expand('%') =~# '_spec\.rb$' |
					\  compiler rspec | setl makeprg=rspec\ \"%:p\" |
					\ else |
					\  compiler ruby | setl makeprg=ruby\ -wc\ \"%:p\" |
					\ endif

" Coffee Script mode: Enable folding
let coffee_folding = 1

" Haskell
au FileType haskell setl et

" Ledger
au BufNewFile,BufRead *.ldg,*.ledger setf ledger | comp ledger
let g:ledger_maxwidth = 80
let g:ledger_fold_blanks = 1
let g:ledger_fillstring = '	»'

" Vimperator textfields
au BufNewFile,BufRead vimperator-www.reddit.com.tmp setf markdown
let g:markdown_fenced_languages = ['coffee', 'css', 'erb=eruby', 'javascript', 'js=javascript', 'json=javascript', 'ruby', 'sass', 'xml', 'html']

" Fish mode for funced
au BufNewFile,BufRead fish_funced.* setf fish

" Haskellmode
"au Bufenter *.hs compiler ghc
"let g:haddock_browser = "firefox"

" CtrlP
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_map = '<Leader>t'
let g:ctrlp_working_path_mode = 'ra'

let g:ctrlp_custom_ignore = {
	\ 'dir':	'\v[\/]\.(git|hg|svn)|bourbon|neat|vendor|node_modules|bower_components$',
	\ 'file': '\v\.(exe|so|dll|pyc|wav|mp3|ogg|blend|swp|jpg|gif|png)$',
	\ }

iab <expr> ddate strftime("%Y/%m/%d")

nnoremap <leader>f :Switch<cr>

" Goyo & Limelight
function! GoyoBefore()
  let b:quitting = 0
  let b:quitting_bang = 0
  autocmd QuitPre <buffer> let b:quitting = 1
  cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!
endfunction

function! GoyoAfter()
  " Quit Vim if this is the only remaining buffer
  if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
    if b:quitting_bang
      qa!
    else
      qa
    endif
  endif

  Limelight!

	" No idea why, but it seems like Limelight messes with my colorscheme
	colorscheme base16-tomorrow-night
endfunction

let g:goyo_callbacks = [function('GoyoBefore'), function('GoyoAfter')]

let g:limelight_conceal_ctermfg = 8
let g:limelight_default_coefficient = 0.7

nnoremap <Leader><space> :Goyo<CR>

" jrnl files
au BufNewFile,BufRead jrnl* set nolist wrap linebreak | Goyo

" DWB external editor
au BufNewFile,BufRead $HOME/.cache/dwb/edit* set nolist wrap linebreak fo+=tnq2 | Goyo

" txt files
au BufEnter *.txt setl tx ts=4 sw=4 fo+=n2

" Syntastic stuff
let g:syntastic_javascript_checkers = ['jsxhint']

let g:syntastic_html_tidy_ignore_errors = [
  \ 'trimming empty <span>'
  \ , ' proprietary attribute "ng-'
  \ , ' proprietary attribute "ui-'
  \ , ' proprietary attribute "tv-'
  \ , '<html> proprietary attribute "class"'
  \ , 'unescaped & which should be written as &amp;'
  \ , '<tv-breadcrumbs> is not recognized!'
  \ , 'discarding unexpected <tv-breadcrumbs>'
  \ , 'discarding unexpected </tv-breadcrumbs>'
  \ ]

let g:syntastic_javascript_jsxhint_quiet_messages = {
	\ "regex": [
	\						"'React' is not defined.",
	\						"Missing 'new' prefix when invoking a constructor.",
	\						"Strings must use singlequote."
	\					 ]
	\ }


" Show syntax group at point
map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>

" vim-pandoc
" let g:pandoc#command#autoexec_on_writes = 0
" let g:pandoc#command#autoexec_command = "Pandoc html5 -s"
let g:pandoc#syntax#conceal#use = 0
let g:pandoc#formatting#mode = "h"
let g:pandoc#folding#level = 10
nnoremap <F9> :Pandoc pdf<CR>
nnoremap <F10> :Pandoc! pdf<CR>

" vim-clang-format
autocmd FileType c,cpp nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
autocmd FileType c,cpp vnoremap <buffer><Leader>cf :ClangFormat<CR>
let g:clang_format#auto_formatexpr = 1
