# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
ABICXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="* -@EULA"
VIDEO_CARDS="amdgpu radeonsi radeon"
CCACHE_DIR="/var/cache/ccache"
ABI_X86="64"

FEATURES="${FEATURES} getbinpkg binpkg-request-signature ccache"
# No dist-kernel, we're on custom-built zen sources
USE="-systemd -wayland -nvidia elogind xinerama dist-kernel"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GRUB_PLATFORMS="efi-64"

GENTOO_MIRRORS="https://us.mirrors.cicku.me/gentoo/ \
    https://es.mirrors.cicku.me/gentoo/ \
    https://fr.mirrors.cicku.me/gentoo/ \
    https://mirror.raiolanetworks.com/gentoo/"
