music_directory     "~/media/music"
playlist_directory  "~/media/music/mpd/playlists"
db_file             "~/media/music/mpd/database"
log_file            "~/media/music/mpd/log"
pid_file            "~/media/music/mpd/pid"
state_file          "~/media/music/mpd/state"
sticker_file        "~/media/music/mpd/sticker.sqlite"

restore_paused      "yes"

bind_to_address     "127.0.0.1"
port                "6600"

audio_output {
    type            "pipewire"
    name            "PipeWire"
    mixer_type      "none"
}
