# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "toml-rb"
gem "vdf"
gem "rexml"

group :test do
  gem "minitest"
  gem "rake"
end

group :development do
  gem "standard"
  gem "bundler-audit"
end
